server.port=8080
spring.application.name=unidad2
spring.datasource.url=jdbc:postgresql://localhost:5432/tienda_db
spring.datasource.username=postgres
spring.datasource.password=sa
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# [REQUERIMIENTO OBLIGATORIO DE JUAN] Pool de Hilos Máximos de Tomcat
server.tomcat.threads.max=200

# Exposición de Métricas para Actuator y Prometheus
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true